name: Test Affected

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: false

concurrency:
  group: 'test-affected-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  test-affected:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/init-monorepo

      - name: Run tests
        uses: ./.github/actions/target-affected
        with:
          target: test
          additional-args: -- --ci --runInBand --passWithNoTests

#      - name: Merge Coverage Reports
#        if: always()
#        run: ./tools/scripts/merge-coverage-reports.sh
#
#      - name: Code Coverage Report
#        if: always()
#        uses: romeovs/lcov-reporter-action@2a28ec3e25fb7eae9cb537e9141603486f810d1a
#        with:
#          title: Code Coverage Report
#          delete-old-comments: true
#          lcov-file: coverage/lcov.info
#
#      - name: Check for Test Results
#        if: success() || failure()
#        id: test-results
#        shell: bash
#        run: |
#          #!/bin/bash
#          FILE=reports/jest/junit.xml
#          if test -f "$FILE"; then
#            echo "Reports file exists at reports/jest/junit.xml"
#            echo "exists=true" >> $GITHUB_OUTPUT
#          fi
#
#      - name: Jest Results
#        if: always() && steps.test-results.outputs.exists == 'true'
#        uses: phoenix-actions/test-reporting@v12
#        with:
#          name: Jest Results            # Name of the check run which will be created
#          path: reports/jest/junit.xml    # Path to test results
#          reporter: jest-junit        # Format of test results
#          fail-on-error: false
